import './globals.css';
export const metadata = {
  title: {
    default:"Testing SEO",
    template:"%s || MyApp"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        </body>
    </html>
  )
}
