import '../globals.css';
export const metadata = {
  title: {
    default: "Testing SEO",
    template: "%s || MyApp"
  },
  description: 'Generated by Next.js',
}

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main>
      <header className=' p-4 text-center text-3xl text-gray-700 bg-gradient-to-r from-cyan-300 to-blue-600 ' >Header</header>
      {children}
      <footer className=' p-4 text-center text-3xl text-gray-700 bg-gradient-to-r from-red-400 to-orange-600  w-full ' >Footer</footer>
    </main>
  )
}
